#### 调用pytest通过python -m pytest
您可以从命令行通过Python解释器调用测试：

    python -m pytest [...]

这几乎等同于直接调用命令行脚本pytest[...],除此之外,通过python调用还会将当前目录添加到sys.path中

#### 可能会看到的退出代码
运行pytest可以产生六种不同的退出码:

Exit code 0:    所有测试均已收集并成功通过  
Exit code 1:    测试被收集并运行，但是一些测试失败了  
Exit code 2:    测试执行被用户中断  
Exit code 3:    执行测试时发生内部错误  
Exit code 4:    pytest命令行使用错误  
Exit code 5:    没有收集任何测试  

它们通过[_pytest.config.ExitCode](https://docs.pytest.org/en/latest/reference.html#_pytest.config.ExitCode)枚举来表示.退出代码是公共API的一部分，可以使用以下方法直接导入和访问:

    from pytest import ExitCode
    
>#### 注意
>如果您想在某些情况下自定义退出代码，尤其是在未收集任何测试的情况下，请考虑使用[pytest-custom exit_code](https://github.com/yashtodi94/pytest-custom_exit_code)插件。  

#### 获取有关版本，选项名称，环境变量的帮助

    pytest --version   # shows where pytest was imported from
    pytest --fixtures  # show available builtin function arguments
    pytest -h | --help # show help on command line and config file options

#### 在第一次(或N次)失败后停止
在第一次(N次)失败后停止测试程序:

    pytest -x           # stop after first failure
    pytest --maxfail=2  # stop after two failures

#### 指定测试/选择测试
Pytest支持的从命令行运行和选择测试的几种方法。  
##### 在模块中运行测试

    pytest test_mod.py

##### 在目录中运行测试

    pytest testing/

##### 通过关键字表达式运行测试

    pytest -k "MyClass and not method"

这将运行包含与给定字符串表达式匹配的名称的测试(不区分大小写)，其中可以包括使用文件名，类名和函数名作为变量的Python运算符。上面的例子将运行 `TestMyClass.test_something`，但不会运行`TestMyClass.test_method_simple`。

##### 通过节点id运行测试
每个收集到的测试都会被分配一个唯一的节点ID，该ID由模块文件名后跟说明符（例如类名，函数名和参数化参数）组成，并用::字符分隔。

要在模块中运行特定的测试，请执行以下操作：

    pytest test_mod.py::test_func

另一个在命令行中指定测试方法的例子:

    pytest test_mod.py::TestClass::test_method

##### 通过标记表达式运行测试

    pytest -m slow

将运行所有用@ pytest.mark.slow装饰器装饰的测试。

有关更多信息，请参见 [marks](https://docs.pytest.org/en/latest/mark.html#mark)。

##### 从包中运行测试

    pytest --pyargs pkg.testing

这将导入`pkg.testing`并使用它的文件系统位置来查找和运行测试。

#### 修改Python的回溯打印

修改回溯打印的示例：

    pytest --showlocals # 在回溯中显示局部变量
    pytest -l           # 显示局部变量(快捷方式)

    pytest --tb=auto    #(默认)对第一个和最后一个条目使用“长”回溯，而对其他条目使用“短”回溯
    pytest --tb=long    # 详尽、丰富的回溯格式
    pytest --tb=short   # 简短的回溯格式
    pytest --tb=line    # 每个失败只显示一行
    pytest --tb=native  # Python标准库格式化
    pytest --tb=no      # 不显示回溯

`--full-trace`会导致在错误时打印很长的跟踪（比`--tb=long`长）。它还可以确保将堆栈跟踪打印在**KeyboardInterrupt**（Ctrl+C）上。如果测试花费的时间太长，并且您使用Ctrl+C中断它们以找出测试挂起的位置，那么这是非常有用的。默认情况下不会显示任何输出(因为pytest捕获了KeyboardInterrupt)。通过使用此选项，可以确保显示跟踪。

#### 详细的总结报告
`-r`标志可用于在测试会话结束时显示“简短的测试摘要信息”，它可以使您更容易的在大型测试套件中清楚的获得所有失败、跳转、xfailed等的情况。  

它默认使用`fE`列出失败和错误。

示例：

    # content of test_example.py
    import pytest
    

    @pytest.fixture
    def error_fixture():
        assert 0
    

    def test_ok():
        print("ok")
    

    def test_fail():
        assert 0
    

    def test_error(error_fixture):
        pass
    

    def test_skip():
        pytest.skip("skipping this test")
    

    def test_xfail():
        pytest.xfail("xfailing this test")
    

    @pytest.mark.xfail(reason="always xfail")
    def test_xpass():
        pass



    $ pytest -ra
    =========================== test session starts ============================
    platform linux -- Python 3.x.y, pytest-5.x.y, py-1.x.y, pluggy-0.x.y
    cachedir: $PYTHON_PREFIX/.pytest_cache
    rootdir: $REGENDOC_TMPDIR
    collected 6 items

    test_example.py .FEsxX                                               [100%]

    ================================== ERRORS ==================================
    _______________________ ERROR at setup of test_error _______________________

        @pytest.fixture
        def error_fixture():
    >       assert 0
    E       assert 0

    test_example.py:6: AssertionError
    ================================= FAILURES =================================
    ________________________________ test_fail _________________________________

        def test_fail():
    >       assert 0
    E       assert 0

    test_example.py:14: AssertionError
    ========================= short test summary info ==========================
    SKIPPED [1] $REGENDOC_TMPDIR/test_example.py:22: skipping this test
    XFAIL test_example.py::test_xfail
      reason: xfailing this test
    XPASS test_example.py::test_xpass always xfail
    ERROR test_example.py::test_error - assert 0
    FAILED test_example.py::test_fail - assert 0
    == 1 failed, 1 passed, 1 skipped, 1 xfailed, 1 xpassed, 1 error in 0.12s ===

`-r`选项接受在后面带一些字符，上面使用的`a`表示“除传递外的所有字符”。

以下是可用字符的完整列表:

* f - failed
* E - error
* s - skipped
* x - xfailed
* X - xpassed
* p - passed
* P - passed with output

（取消）选择组的特殊字符：

* a - all except `pP`
* A - all
* N - none, this can be used to display nothing (since fE is the default)

可以使用多个字符，例如，仅查看失败和跳过的测试，可以执行：

        $ pytest -rfs
    =========================== test session starts ============================
    platform linux -- Python 3.x.y, pytest-5.x.y, py-1.x.y, pluggy-0.x.y
    cachedir: $PYTHON_PREFIX/.pytest_cache
    rootdir: $REGENDOC_TMPDIR
    collected 6 items

    test_example.py .FEsxX                                               [100%]

    ================================== ERRORS ==================================
    _______________________ ERROR at setup of test_error _______________________

        @pytest.fixture
        def error_fixture():
    >       assert 0
    E       assert 0

    test_example.py:6: AssertionError
    ================================= FAILURES =================================
    ________________________________ test_fail _________________________________

        def test_fail():
    >       assert 0
    E       assert 0

    test_example.py:14: AssertionError
    ========================= short test summary info ==========================
    FAILED test_example.py::test_fail - assert 0
    SKIPPED [1] $REGENDOC_TMPDIR/test_example.py:22: skipping this test
    == 1 failed, 1 passed, 1 skipped, 1 xfailed, 1 xpassed, 1 error in 0.12s ===

使用`p`列出了通过的测试，而`p`增加了一个额外的部分“PASSES”来获取那些已被捕获的测试通过的输出:

    $ pytest -rpP
    =========================== test session starts ============================
    platform linux -- Python 3.x.y, pytest-5.x.y, py-1.x.y, pluggy-0.x.y
    cachedir: $PYTHON_PREFIX/.pytest_cache
    rootdir: $REGENDOC_TMPDIR
    collected 6 items

    test_example.py .FEsxX                                               [100%]

    ================================== ERRORS ==================================
    _______________________ ERROR at setup of test_error _______________________

        @pytest.fixture
        def error_fixture():
    >       assert 0
    E       assert 0

    test_example.py:6: AssertionError
    ================================= FAILURES =================================
    ________________________________ test_fail _________________________________

        def test_fail():
    >       assert 0
    E       assert 0

    test_example.py:14: AssertionError
    ================================== PASSES ==================================
    _________________________________ test_ok __________________________________
    --------------------------- Captured stdout call ---------------------------
    ok
    ========================= short test summary info ==========================
    PASSED test_example.py::test_ok
    == 1 failed, 1 passed, 1 skipped, 1 xfailed, 1 xpassed, 1 error in 0.12s ===

#### 失败时切换到PDB (Python调试器)
Python附带一个名为PDB的内置Python调试器。pytest允许用户通过命令行选项进入PDB提示符:

    pytest --pdb

这将在每次失败(或KeyboardInterrupt)时调用Python调试器。通常，您可能只想在第一次失败测试时这样做，以了解特定的失败情况:

    pytest -x --pdb   # 在第一次失败时切换到PDB，然后结束测试会话
    pytest --pdb --maxfail=3  # 如果前三次失败，就切换到PDB

请注意，在发生任何故障时，都会将异常信息存储在 `sys.last_value`，      `sys.last_type`和 `sys.last_traceback`中。在交互式使用中，这使您可以使用任何调试工具进行事后调试。您还可以手动访问异常信息，例如：

    >>> import sys
    >>> sys.last_traceback.tb_lineno
    42
    >>> sys.last_value
    AssertionError('assert result == "ok"',)

#### 在测试开始时跳到PDB (Python调试器)
`pytest`允许用户在每次测试开始时通过命令行选项立即进入PDB提示符:

    pytest --trace

这将在每次测试开始时调用Python调试器。

#### 设置断点
要在代码中设置断点，请使用本机Python导入pdb;在您的代码中调用pdb.set_trace()， pytest会自动禁用该测试的输出捕获:

* 其他测试中的输出捕获不受影响。
* 任何先前已捕获的测试输出将照原样处理。
* 当结束调试器会话时（通过continue命令），将恢复输出捕获。

#### 使用内置的断点函数
Python 3.7引入了内置的breakpoint()函数。Pytest支持通过以下行为使用breakpoint()：

* 当调用`breakpoint()`并将`PYTHONBREAKPOINT`设置为默认值时,pytest将使用自定义内部PDB跟踪UI，而不是系统默认的`Pdb`。
* 测试完成后，系统将默认返回系统`Pdb`跟踪UI。
* 通过将`--pdb`传递给pytest，可以将定制的内部pdb跟踪UI与`breakpoint()`和失败的测试/未处理的异常一起使用。
* `--pdbcls`可用于指定自定义调试器类。

#### 分析测试执行时间
要获取最慢的10个测试持续时间的列表，请执行以下操作：

    pytest --durations=10

默认情况下，除非在命令行上传递-vv，否则pytest不会显示太短的测试持续时间（<0.01s）。

#### 错误处理程序
5.0版中的新功能。  

[faulthandler](https://docs.python.org/3/library/faulthandler.html) 标准模块可用于在分段错误或超时之后转储Python回溯。

该模块会自动启用pytest运行，除非在命令行上给出了`-p no：faulthandler`。

此外，如果一个测试的完成时间超过X秒(在Windows上不可用)，可以使用faulthandler timeout=X配置选项来转储所有线程的回溯。

>注意  
>这个功能是由外部[pytest-faulthandler](https://github.com/pytest-dev/pytest-faulthandler)插件集成的,有两个小的区别:
>* 要禁用它，使用-p no:faulthandler 而不是——no-faulthandler:前者可以与任何插件一起使用，因此它可以保存一个选项。
>* [faulthandler-timeout](https://docs.pytest.org/en/latest/reference.html#confval-faulthandler_timeout)命令行选项已成为faulthandler_timeout配置选项。仍然可以使用-o faulthandler_timeout = X从命令行进行配置。

#### 创建JUnitXML格式的文件
要创建可被Jenkins或其他持续集成服务器读取的结果文件，请使用以下调用：

    pytest --junitxml=path

在路径上创建XML文件。

要设置根测试套件xml项的名称，可以在配置文件中配置`junit_suite_name`选项：

    [pytest]
    junit_suite_name = my_suite
    
版本4.0中的新功能。

JUnit XML规范似乎表明`“time”`属性应该报告总的测试执行时间,包括设置和拆卸([1](http://windyroad.com.au/dl/Open%20Source/JUnit.xsd),[2](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_14.1.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html))。这是默认的pytest行为。若要只报告调用持续时间，请像这样配置`junit_duration_report`选项:

    [pytest]
    junit_duration_report = call

##### 记录属性
如果您想为测试记录额外的信息，您可以使用`record_property` fixture:

    def test_function(record_property):
        record_property("example_key", 1)
        assert True
    
这将向生成的`testcase`标签添加一个额外的属性`example_key="1"`:

    <testcase classname="test_function" file="test_function.py" line="0" name="test_function" time="0.0009">
      <properties>
        <property name="example_key" value="1" />
      </properties>
    </testcase>

`name`必须是一个字符串，`value`将被转换为一个字符串，并正确地进行xml转义。

生成的XML与最新的`xunit`标准兼容,与[record_property](https://docs.pytest.org/en/latest/usage.html#record-property)和[record_xml_attribute](https://docs.pytest.org/en/latest/usage.html#record-xml-attribute)相反。

#### 创建resultlog格式的文件
要创建机器可读的纯文本结果文件，您可以发出:

    pytest --resultlog=path

并在`path`位置查看内容。这些文件被 [PyPy-test](http://buildbot.pypy.org/summary) web页面用于显示经过多次修订的测试结果。

><font size="4">警告</font>  
>此选项很少使用，并计划在pytest 6.0中删除。  
    >如果使用此选项，请考虑使用新的[pytest-reportlog](https://github.com/pytest-dev/pytest-reportlog)插件。  
>有关更多信息，请参见[弃用文档](https://docs.pytest.org/en/latest/deprecations.html#result-log-result-log)。

#### 将测试报告发送到在线pastebin服务

为每个失败的测试创建一个URL：

    pytest --pastebin=failed

这将向远程Paste服务提交测试运行信息，并为每次失败提供URL。您可以像往常一样选择测试，或者如果只想发送一个特定的失败，则可以添加例如`-x`。

##### 为整个测试会话日志创建URL：

    pytest --pastebin=all

目前只实现了对 [http://bpaste.net](http://bpaste.net/) 服务的pasting。

在5.2版中进行了更改。

如果创建URL由于任何原因失败，则会生成警告，而不是使整个测试套件失败。

#### 提前加载插件
您可以使用`-p`选项在命令行中显式地提前加载插件(内部和外部)

    pytest -p mypluginmodule

该选项接收一个`name`参数，它可以是:

* 一个完整的模块点名，例如`myproject.plugins`。这个点名必须是可输入的。
* 插件的入口点名称。这是注册插件时传递给`setuptools`的名称。例如，要提前加载 [pytest-cov](https://pypi.org/project/pytest-cov/) 插件，可以使用：


    pytest -p pytest_cov
    
#### 禁用插件
要在调用时禁用加载特定的插件，请使用-p选项和前缀no:。

示例:要禁用加载插件`doctest`(负责从文本文件执行doctest测试)，可以像这样调用:

    pytest -p no:doctest

#### 从Python代码中调用pytest

您可以直接从Python代码调用`pytest`：

    pytest.main()

就像您从命令行调用“ pytest”一样。它不会引发SystemExit，而是返回exitcode。
您可以传递选项和参数：

    pytest.main(["-x", "mytestdir"])

您可以为`pytest.main`指定额外的插件:

    # content of myinvoke.py
    import pytest
    

    class MyPlugin:
        def pytest_sessionfinish(self):
            print("*** test run reporting finishing")
    

    pytest.main(["-qq"], plugins=[MyPlugin()])

运行它将显示添加了`MyPlugin`并调用了它的钩子:

    $ python myinvoke.py
    .FEsxX.                                                              [100%]*** test run reporting finishing

    ================================== ERRORS ==================================
    _______________________ ERROR at setup of test_error _______________________

        @pytest.fixture
        def error_fixture():
    >       assert 0
    E       assert 0

    test_example.py:6: AssertionError
    ================================= FAILURES =================================
    ________________________________ test_fail _________________________________

        def test_fail():
    >       assert 0
    E       assert 0

    test_example.py:14: AssertionError
    ========================= short test summary info ==========================
    FAILED test_example.py::test_fail - assert 0
    ERROR test_example.py::test_error - assert 0

> <font size = 4>注意：</font>  
> 调用pytest.main()将导入您的测试和它们导入的任何模块。  
> 由于python导入系统的缓存机制，从同一个进程中对pytest.main()进行后续调用不会反映调用之间对这些文件的更改。由于这个原因，不建议从同一个进程多次调用(例如，为了重新运行测试)pytest.main()












